build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related production change APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "{cipher}fbe419765526ba75a8bc42eaafe5237100fc2d146843f0c03eff980900825cbd76ab60d2058787663980ddf7c7b3f4f1"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956
