build:
  version: "3.0"

loans:
  message: "Welcome to Afrid's bank loans related default APIs "
  contactDetails:
    name: "Sekh Afrid - Senior Consultant"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
